language: node_js
node_js: stable
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache: npm
script:
- npm test
env:
  global:
  - secure: MFJhuwsLZHH5aOWugM8YslBOTUS54zXU1sEtT3VT9+JJnWYc0c4NpvbNNBswVM1Gs0EixAXO1xStbCCZB/+s63ndivYPtiChcjaC2y43rGGQlrCbPc78MRJ5Zl9V87fxfJxNpufpzWSdeyxjs9uJyZt24hriLR1hcgdRWGMoiMK69AHWV96656d9/nPbplTYFqrQbIEX8Vw1BSUqLW9Ctb8JaiCkkWKqMmS8+CHkfvCqmqAowftmJjnx+kye+1RkgrqZ+qw7Uh1W7fSFoB2XFjwg6MGQL7lKfV5Q8qaHv3iNP2gQEHUzPWVpJTT5UuVq0A5XMYSPrNdROxVqpDhAvS+VX11oRBIhKDvFW/J88CufQu3WqZ0Dk5sWQMAGVAOahd6tMHfKxCd4vBFBcOPRz/GGDnbuW0BJBBnWK6zBKtk7UdU4IBe6qlYofYN6TrmM/Xw/9mA48dE8njPqzQL0S8IL8FweLSV0pMclMVKyrX4TTEIOoVD1tG6LigKhPp9UNl0xP/ifx042FD2rr3pc9RQmiXlu7SdnVLoIMtiaX54WiBOdol+krGNYkHW9MUT9Vn36PzZKGpakbAt5w2Svuf/oC6HhK8uxqCBM20jShBEkSGoV1Z9bjBQFnHy6jI+vHRZEADQGhNmvafZ6CNX0B4F6GfAdtbkDNTZcBy/DP6U=
  - secure: f+D5i0nJYGqe/4BgJi+6Rw9difdY7Y4j/uuuaKWJ65AMR4HWN504Si6G2M8dOR2oCaguvG791NmnMJeu/PxeO+t1JXmAOEb5NLMW1SqZoS0Fvlmbc9l8VY3J04XtUe2zXJCaRvgtcnPxoOPwD67UpnIiozNVayor3+6sVDlXyMWI+loDyFJrURjEX8a9mQj9bV0wv6X0oJvU3uwYuHFxMhNpq+4iWzkD3KU9DYZWYsR1KxLEwoxWYGSQr6Pp6o/xOaIFTf/tm1gf22/6cQD5my0p6dqCYn5usuTLGtXA04oLrsL5hr1P0flHns+MlePd2iiCRmjEWa/dvGeqG46Sden9WW9/UXdOB7xf3AeKGsu4/qq1FvnFCF6ihKCFxpFfOfyrq2fPgeM7wMyliEwVEG5zjS3Hp3UzFhDesI2wxeRruY6tc+rzn/I1UFQYFqx0K3nye+rbA4630YxjWLGm+PnJLJ61ImWugK41ZyDVJG1uYhOUERcbJXDLIewwgfu8t7c+gkv8xDJieP3sscrbXMivwR7mqtfKwQyWe1w3GsUqZCTResS46Q6SmRaM2EaKfMR4JHLRrdAgr4wcTzr+3lU7TBHe5LKwABzyesIO3qFxw52/jT6baqJRzg+zafj8Jx1x6xBEysyz6szu4teZpdHFpbGykiep7mhxQD9ulzE=
